### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by YES-12**

### CODE REVIEW

**Comment by DanKGooGLy** [comment]
What does this do?

**Comment by YES-12** [comment]
It makes it so that when someone clickes on the shortlink, it opens on a new tab

**Comment by DanKGooGLy** [comment]
Oh yeah, I forgot. The only downside to this is that when you open the new tab, if you click another link on our domain then it replaces the last new tab you opened.

**Comment by DanKGooGLy** [comment]
I'll merge it.

**Comment by YES-12** [comment]
ok thanks

**Comment by YES-12** [comment]
it was annoying to click on th link and have it open on the same tab

**Pull request merged**
