### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by savageboy165**

### CODE REVIEW

**Comment by DanKGooGLy** [comment]
I'll fix it later, just testing iframe embeds

**Comment by savageboy165** [comment]
ok

**Comment by savageboy165** [comment]
did i do it right tho

**Comment by DanKGooGLy** [comment]
I'll see.

**Comment by savageboy165** [comment]
ok

**Comment by DanKGooGLy** [comment]
Looks about good, but I'm going to close this PR

**Comment by savageboy165** [comment]
what does that mean

**Comment by DanKGooGLy** [comment]
Pull request

When you merge it, it means you approve it and make it official
When you close it, it means you deny it

**Comment by savageboy165** [comment]
wdym about deny

**Comment by DanKGooGLy** [comment]
Approve a pull request or deny it

**Comment by savageboy165** [comment]
so if i script something then you don't have to approve it

**Comment by DanKGooGLy** [comment]
When you "script something", you make a pull request to this main repository, which I can then merge or close.

**Comment by savageboy165** [comment]
oh

**Comment by savageboy165** [comment]
so do i still have to ask you

**Comment by DanKGooGLy** [comment]
I can give you write perms, but I believe its better for you to PR so I can review any faulty code in it.
Plus I check my github 24/7 so I won't miss a PR

**Comment by savageboy165** [comment]
ok

**Pull request closed without merging**
